#!/bin/bash


version_str_on_github() {
    echo "Checking updates on GitHub..."
    url_base="https://raw.githubusercontent.com/TinkerTools/tinker9/master/ext/interface"
    vnum=$(curl -s "$url_base/version.txt")
    if [[ $vnum =~ ^-?[0-9]+$ ]]; then
        # If vnum is a valid integer, compare it to the local version number.
        lnum=$(cat version.txt)
        if [ $lnum -lt $vnum ]; then
            echo Updating from GitHub...
            curl -O "$url_base/export"
            curl -O "$url_base/parse.py"
            curl -O "$url_base/version.txt"
            echo "Update completed. Please run this command again."
            exit 0
        else
            echo "Already the newest."
        fi
    else
        echo Cannot check the version on GitHub. Skipping the update...
    fi
}


export_c() {
    mkdir -p c
    rm -rf c/*
    mkdir -p c/tinker/detail

    cd c/tinker
    python3 ../../parse.py --lang=c $src_dir/*.f | bash
    mv CMakeLists.txt ..
    cd ../..
}


export_cpp() {
    mkdir -p cpp
    rm -rf cpp/*
    mkdir -p cpp/tinker/detail

    cd cpp/tinker
    python3 ../../parse.py --lang=cpp $src_dir/*.f | bash
    mv CMakeLists.txt ..
    cd ../..
}


src_dir=$(realpath ../source)
export LC_COLLATE=C


# check updates
version_str_on_github


for a in "$@"; do
    if [ "$a" = c ]; then
        echo "Exporting the C interface..."
        export_c
    elif [ "$a" = cpp ]; then
        echo "Exporting the C++ interface..."
        export_cpp
    fi
done
