#ifndef TINKER_MOD_MERCK_HH_
#define TINKER_MOD_MERCK_HH_

#include "util/macro.h"
#include "sizes.hh"

TINKER_NAMESPACE_BEGIN namespace merck {
using namespace sizes;

extern int& nlignes;
extern int (&bt_1)[2][500];
extern int (&eqclass)[5][500];
extern int (&crd)[100];
extern int (&val)[100];
extern int (&pilp)[100];
extern int (&mltb)[100];
extern int (&arom)[100];
extern int (&lin)[100];
extern int (&sbmb)[100];
extern int (&mmffarom)[6][maxtyp];
extern int (&mmffaromc)[6][maxtyp];
extern int (&mmffaroma)[6][maxtyp];
extern double (&rad0)[100];
extern double (&paulel)[100];
extern double (&r0ref)[100][100];
extern double (&kbref)[100][100];
extern double (&mmff_kb)[100][100];
extern double (&mmff_kb1)[100][100];
extern double (&mmff_b0)[100][100];
extern double (&mmff_b1)[100][100];
extern double*& mmff_ka;
extern double*& mmff_ka1;
extern double*& mmff_ka2;
extern double*& mmff_ka3;
extern double*& mmff_ka4;
extern double*& mmff_ka5;
extern double*& mmff_ka6;
extern double*& mmff_ka7;
extern double*& mmff_ka8;
extern double*& mmff_ang0;
extern double*& mmff_ang1;
extern double*& mmff_ang2;
extern double*& mmff_ang3;
extern double*& mmff_ang4;
extern double*& mmff_ang5;
extern double*& mmff_ang6;
extern double*& mmff_ang7;
extern double*& mmff_ang8;
extern double*& stbn_abc;
extern double*& stbn_cba;
extern double*& stbn_abc1;
extern double*& stbn_cba1;
extern double*& stbn_abc2;
extern double*& stbn_cba2;
extern double*& stbn_abc3;
extern double*& stbn_cba3;
extern double*& stbn_abc4;
extern double*& stbn_cba4;
extern double*& stbn_abc5;
extern double*& stbn_cba5;
extern double*& stbn_abc6;
extern double*& stbn_cba6;
extern double*& stbn_abc7;
extern double*& stbn_cba7;
extern double*& stbn_abc8;
extern double*& stbn_cba8;
extern double*& stbn_abc9;
extern double*& stbn_cba9;
extern double*& stbn_abc10;
extern double*& stbn_cba10;
extern double*& stbn_abc11;
extern double*& stbn_cba11;
extern double (&defstbn_abc)[5][5][5];
extern double (&defstbn_cba)[5][5][5];
extern double (&t1_1)[2001][2];
extern double (&t2_1)[2001][2];
extern double (&t3_1)[2001][2];
extern double (&t1_2)[2001][2];
extern double (&t2_2)[2001][2];
extern double (&t3_2)[2001][2];
extern char (&kt_1)[2001][16];
extern char (&kt_2)[2001][16];
extern double (&g)[maxclass];
extern double (&alph)[maxclass];
extern double (&nn)[maxclass];
extern char (&da)[maxclass][1];
extern double (&bci)[100][100];
extern double (&bci_1)[100][100];
extern double (&pbci)[maxclass];
extern double (&fcadj)[maxclass];

#ifdef TINKER_MOD_CPP_
extern "C" int m_tinker_mod(merck, nlignes);
extern "C" int m_tinker_mod(merck, bt_1)[2][500];
extern "C" int m_tinker_mod(merck, eqclass)[5][500];
extern "C" int m_tinker_mod(merck, crd)[100];
extern "C" int m_tinker_mod(merck, val)[100];
extern "C" int m_tinker_mod(merck, pilp)[100];
extern "C" int m_tinker_mod(merck, mltb)[100];
extern "C" int m_tinker_mod(merck, arom)[100];
extern "C" int m_tinker_mod(merck, lin)[100];
extern "C" int m_tinker_mod(merck, sbmb)[100];
extern "C" int m_tinker_mod(merck, mmffarom)[6][maxtyp];
extern "C" int m_tinker_mod(merck, mmffaromc)[6][maxtyp];
extern "C" int m_tinker_mod(merck, mmffaroma)[6][maxtyp];
extern "C" double m_tinker_mod(merck, rad0)[100];
extern "C" double m_tinker_mod(merck, paulel)[100];
extern "C" double m_tinker_mod(merck, r0ref)[100][100];
extern "C" double m_tinker_mod(merck, kbref)[100][100];
extern "C" double m_tinker_mod(merck, mmff_kb)[100][100];
extern "C" double m_tinker_mod(merck, mmff_kb1)[100][100];
extern "C" double m_tinker_mod(merck, mmff_b0)[100][100];
extern "C" double m_tinker_mod(merck, mmff_b1)[100][100];
extern "C" double* m_tinker_mod(merck, mmff_ka);
extern "C" double* m_tinker_mod(merck, mmff_ka1);
extern "C" double* m_tinker_mod(merck, mmff_ka2);
extern "C" double* m_tinker_mod(merck, mmff_ka3);
extern "C" double* m_tinker_mod(merck, mmff_ka4);
extern "C" double* m_tinker_mod(merck, mmff_ka5);
extern "C" double* m_tinker_mod(merck, mmff_ka6);
extern "C" double* m_tinker_mod(merck, mmff_ka7);
extern "C" double* m_tinker_mod(merck, mmff_ka8);
extern "C" double* m_tinker_mod(merck, mmff_ang0);
extern "C" double* m_tinker_mod(merck, mmff_ang1);
extern "C" double* m_tinker_mod(merck, mmff_ang2);
extern "C" double* m_tinker_mod(merck, mmff_ang3);
extern "C" double* m_tinker_mod(merck, mmff_ang4);
extern "C" double* m_tinker_mod(merck, mmff_ang5);
extern "C" double* m_tinker_mod(merck, mmff_ang6);
extern "C" double* m_tinker_mod(merck, mmff_ang7);
extern "C" double* m_tinker_mod(merck, mmff_ang8);
extern "C" double* m_tinker_mod(merck, stbn_abc);
extern "C" double* m_tinker_mod(merck, stbn_cba);
extern "C" double* m_tinker_mod(merck, stbn_abc1);
extern "C" double* m_tinker_mod(merck, stbn_cba1);
extern "C" double* m_tinker_mod(merck, stbn_abc2);
extern "C" double* m_tinker_mod(merck, stbn_cba2);
extern "C" double* m_tinker_mod(merck, stbn_abc3);
extern "C" double* m_tinker_mod(merck, stbn_cba3);
extern "C" double* m_tinker_mod(merck, stbn_abc4);
extern "C" double* m_tinker_mod(merck, stbn_cba4);
extern "C" double* m_tinker_mod(merck, stbn_abc5);
extern "C" double* m_tinker_mod(merck, stbn_cba5);
extern "C" double* m_tinker_mod(merck, stbn_abc6);
extern "C" double* m_tinker_mod(merck, stbn_cba6);
extern "C" double* m_tinker_mod(merck, stbn_abc7);
extern "C" double* m_tinker_mod(merck, stbn_cba7);
extern "C" double* m_tinker_mod(merck, stbn_abc8);
extern "C" double* m_tinker_mod(merck, stbn_cba8);
extern "C" double* m_tinker_mod(merck, stbn_abc9);
extern "C" double* m_tinker_mod(merck, stbn_cba9);
extern "C" double* m_tinker_mod(merck, stbn_abc10);
extern "C" double* m_tinker_mod(merck, stbn_cba10);
extern "C" double* m_tinker_mod(merck, stbn_abc11);
extern "C" double* m_tinker_mod(merck, stbn_cba11);
extern "C" double m_tinker_mod(merck, defstbn_abc)[5][5][5];
extern "C" double m_tinker_mod(merck, defstbn_cba)[5][5][5];
extern "C" double m_tinker_mod(merck, t1_1)[2001][2];
extern "C" double m_tinker_mod(merck, t2_1)[2001][2];
extern "C" double m_tinker_mod(merck, t3_1)[2001][2];
extern "C" double m_tinker_mod(merck, t1_2)[2001][2];
extern "C" double m_tinker_mod(merck, t2_2)[2001][2];
extern "C" double m_tinker_mod(merck, t3_2)[2001][2];
extern "C" char m_tinker_mod(merck, kt_1)[2001][16];
extern "C" char m_tinker_mod(merck, kt_2)[2001][16];
extern "C" double m_tinker_mod(merck, g)[maxclass];
extern "C" double m_tinker_mod(merck, alph)[maxclass];
extern "C" double m_tinker_mod(merck, nn)[maxclass];
extern "C" char m_tinker_mod(merck, da)[maxclass][1];
extern "C" double m_tinker_mod(merck, bci)[100][100];
extern "C" double m_tinker_mod(merck, bci_1)[100][100];
extern "C" double m_tinker_mod(merck, pbci)[maxclass];
extern "C" double m_tinker_mod(merck, fcadj)[maxclass];

int& nlignes = m_tinker_mod(merck, nlignes);
int (&bt_1)[2][500] = m_tinker_mod(merck, bt_1);
int (&eqclass)[5][500] = m_tinker_mod(merck, eqclass);
int (&crd)[100] = m_tinker_mod(merck, crd);
int (&val)[100] = m_tinker_mod(merck, val);
int (&pilp)[100] = m_tinker_mod(merck, pilp);
int (&mltb)[100] = m_tinker_mod(merck, mltb);
int (&arom)[100] = m_tinker_mod(merck, arom);
int (&lin)[100] = m_tinker_mod(merck, lin);
int (&sbmb)[100] = m_tinker_mod(merck, sbmb);
int (&mmffarom)[6][maxtyp] = m_tinker_mod(merck, mmffarom);
int (&mmffaromc)[6][maxtyp] = m_tinker_mod(merck, mmffaromc);
int (&mmffaroma)[6][maxtyp] = m_tinker_mod(merck, mmffaroma);
double (&rad0)[100] = m_tinker_mod(merck, rad0);
double (&paulel)[100] = m_tinker_mod(merck, paulel);
double (&r0ref)[100][100] = m_tinker_mod(merck, r0ref);
double (&kbref)[100][100] = m_tinker_mod(merck, kbref);
double (&mmff_kb)[100][100] = m_tinker_mod(merck, mmff_kb);
double (&mmff_kb1)[100][100] = m_tinker_mod(merck, mmff_kb1);
double (&mmff_b0)[100][100] = m_tinker_mod(merck, mmff_b0);
double (&mmff_b1)[100][100] = m_tinker_mod(merck, mmff_b1);
double*& mmff_ka = m_tinker_mod(merck, mmff_ka);
double*& mmff_ka1 = m_tinker_mod(merck, mmff_ka1);
double*& mmff_ka2 = m_tinker_mod(merck, mmff_ka2);
double*& mmff_ka3 = m_tinker_mod(merck, mmff_ka3);
double*& mmff_ka4 = m_tinker_mod(merck, mmff_ka4);
double*& mmff_ka5 = m_tinker_mod(merck, mmff_ka5);
double*& mmff_ka6 = m_tinker_mod(merck, mmff_ka6);
double*& mmff_ka7 = m_tinker_mod(merck, mmff_ka7);
double*& mmff_ka8 = m_tinker_mod(merck, mmff_ka8);
double*& mmff_ang0 = m_tinker_mod(merck, mmff_ang0);
double*& mmff_ang1 = m_tinker_mod(merck, mmff_ang1);
double*& mmff_ang2 = m_tinker_mod(merck, mmff_ang2);
double*& mmff_ang3 = m_tinker_mod(merck, mmff_ang3);
double*& mmff_ang4 = m_tinker_mod(merck, mmff_ang4);
double*& mmff_ang5 = m_tinker_mod(merck, mmff_ang5);
double*& mmff_ang6 = m_tinker_mod(merck, mmff_ang6);
double*& mmff_ang7 = m_tinker_mod(merck, mmff_ang7);
double*& mmff_ang8 = m_tinker_mod(merck, mmff_ang8);
double*& stbn_abc = m_tinker_mod(merck, stbn_abc);
double*& stbn_cba = m_tinker_mod(merck, stbn_cba);
double*& stbn_abc1 = m_tinker_mod(merck, stbn_abc1);
double*& stbn_cba1 = m_tinker_mod(merck, stbn_cba1);
double*& stbn_abc2 = m_tinker_mod(merck, stbn_abc2);
double*& stbn_cba2 = m_tinker_mod(merck, stbn_cba2);
double*& stbn_abc3 = m_tinker_mod(merck, stbn_abc3);
double*& stbn_cba3 = m_tinker_mod(merck, stbn_cba3);
double*& stbn_abc4 = m_tinker_mod(merck, stbn_abc4);
double*& stbn_cba4 = m_tinker_mod(merck, stbn_cba4);
double*& stbn_abc5 = m_tinker_mod(merck, stbn_abc5);
double*& stbn_cba5 = m_tinker_mod(merck, stbn_cba5);
double*& stbn_abc6 = m_tinker_mod(merck, stbn_abc6);
double*& stbn_cba6 = m_tinker_mod(merck, stbn_cba6);
double*& stbn_abc7 = m_tinker_mod(merck, stbn_abc7);
double*& stbn_cba7 = m_tinker_mod(merck, stbn_cba7);
double*& stbn_abc8 = m_tinker_mod(merck, stbn_abc8);
double*& stbn_cba8 = m_tinker_mod(merck, stbn_cba8);
double*& stbn_abc9 = m_tinker_mod(merck, stbn_abc9);
double*& stbn_cba9 = m_tinker_mod(merck, stbn_cba9);
double*& stbn_abc10 = m_tinker_mod(merck, stbn_abc10);
double*& stbn_cba10 = m_tinker_mod(merck, stbn_cba10);
double*& stbn_abc11 = m_tinker_mod(merck, stbn_abc11);
double*& stbn_cba11 = m_tinker_mod(merck, stbn_cba11);
double (&defstbn_abc)[5][5][5] = m_tinker_mod(merck, defstbn_abc);
double (&defstbn_cba)[5][5][5] = m_tinker_mod(merck, defstbn_cba);
double (&t1_1)[2001][2] = m_tinker_mod(merck, t1_1);
double (&t2_1)[2001][2] = m_tinker_mod(merck, t2_1);
double (&t3_1)[2001][2] = m_tinker_mod(merck, t3_1);
double (&t1_2)[2001][2] = m_tinker_mod(merck, t1_2);
double (&t2_2)[2001][2] = m_tinker_mod(merck, t2_2);
double (&t3_2)[2001][2] = m_tinker_mod(merck, t3_2);
char (&kt_1)[2001][16] = m_tinker_mod(merck, kt_1);
char (&kt_2)[2001][16] = m_tinker_mod(merck, kt_2);
double (&g)[maxclass] = m_tinker_mod(merck, g);
double (&alph)[maxclass] = m_tinker_mod(merck, alph);
double (&nn)[maxclass] = m_tinker_mod(merck, nn);
char (&da)[maxclass][1] = m_tinker_mod(merck, da);
double (&bci)[100][100] = m_tinker_mod(merck, bci);
double (&bci_1)[100][100] = m_tinker_mod(merck, bci_1);
double (&pbci)[maxclass] = m_tinker_mod(merck, pbci);
double (&fcadj)[maxclass] = m_tinker_mod(merck, fcadj);
#endif

} TINKER_NAMESPACE_END

#endif
