#pragma once
#include "const.h"
// #include "erfc.h"
// #include "fsinhcimpl.h"
// #include "inc.h"
#include "libfunc.h"
#include "lu.h"
#include "maxmin.h"
#include "ou.h"
// #include "parallel_acc.h"
// #include "parallel_cu.h"
#include "parallel.h"
#include "pow2.h"
#include "random.h"
#include "sinhc.h"
#include "trimatexp.h"
