#define TINKER_EXTERN_DEFINITION_FILE 1

#include "mod/accasync.h"
#include "mod/atom.h"
#include "mod/box.h"
#include "mod/cudalib.h"
#include "mod/disp.h"
#include "mod/elec.h"
#include "mod/elecamoeba.h"
#include "mod/elechippo.h"
#include "mod/elecpchg.h"
#include "mod/energy.h"
#include "mod/evalence.h"
#include "mod/gpucard.h"
#include "mod/md.h"
#include "mod/molecule.h"
#include "mod/mutant.h"
#include "mod/nblist.h"
#include "mod/platform.h"
#include "mod/rattle.h"
#include "mod/repel.h"
#include "mod/vdw.h"
