#!/bin/bash


# This program checks the version of the Fortran compiler and the version
# of the c++ compiler that the PGI compiler is configured to, assuming the
# default c++ and Fortran compilers are of the same vendor.


# Run this program in a configured cmake build directory.
# cd build; ../cmake/check-pgi


if [ ! -f CMakeCache.txt ]; then
   echo No CMakeCache.txt was found.
   exit
fi


ACC_COMPILER=$(grep T9_ACC_COMPILER CMakeCache.txt | cut -d '=' -f 2-)
if [ $ACC_COMPILER = '' ]; then
   echo No OpenACC compiler was used.
   exit
fi
PGI_GCCVERSION=$(makelocalrc -o | grep "GCC version" | awk '{print $4}')


FORTRAN_COMPILER=$(grep CMAKE_Fortran_COMPILER:FILEPATH CMakeCache.txt | cut -d '=' -f 2-)
GCCVERSION=$($FORTRAN_COMPILER --version | grep GNU | awk '{print $NF}')


CONCLUDE () {
   echo "ACC Compiler:         " $ACC_COMPILER
   echo "ACC is configured to: " Version $PGI_GCCVERSION "(of the Fortran compiler)"
   echo "Fortran Compiler:     " Version $GCCVERSION
}
CONCLUDE
