#ifndef TINKER_MOD_FACES_HH_
#define TINKER_MOD_FACES_HH_

#include "macro.h"

TINKER_NAMESPACE_BEGIN namespace faces {
extern int& maxcls;
extern int& maxtt;
extern int& maxt;
extern int& maxp;
extern int& maxv;
extern int& maxen;
extern int& maxfn;
extern int& maxc;
extern int& maxep;
extern int& maxfs;
extern int& maxcy;
extern int& mxcyep;
extern int& maxfp;
extern int& mxfpcy;
extern int& na;
extern double& pr;
extern double*& ar;
extern double*& axyz;
extern int*& skip;
extern int*& nosurf;
extern int*& afree;
extern int*& abur;
extern int*& cls;
extern int*& clst;
extern int*& acls;
extern int& ntt;
extern int*& ttfe;
extern int*& ttle;
extern int*& enext;
extern int*& tta;
extern int*& ttbur;
extern int*& ttfree;
extern int& nt;
extern int*& tfe;
extern int*& ta;
extern double*& tr;
extern double*& t;
extern double*& tax;
extern int*& tfree;
extern int& np;
extern int*& pa;
extern double*& p;
extern int& nv;
extern int*& va;
extern int*& vp;
extern double*& vxyz;
extern int& nen;
extern int& nfn;
extern int*& env;
extern int*& fnen;
extern int& nc;
extern int*& ca;
extern int*& ct;
extern double*& cr;
extern double*& c;
extern int& nep;
extern int*& epc;
extern int*& epv;
extern int*& afe;
extern int*& ale;
extern int*& epnext;
extern int& nfs;
extern int*& fsen;
extern int*& fsep;
extern int& ncy;
extern int*& cynep;
extern int*& cyep;
extern int& nfp;
extern int*& fpa;
extern int*& fpncy;
extern int*& fpcy;

#ifdef TINKER_MOD_CPP_
extern "C" int TINKER_MOD(faces, maxcls);
extern "C" int TINKER_MOD(faces, maxtt);
extern "C" int TINKER_MOD(faces, maxt);
extern "C" int TINKER_MOD(faces, maxp);
extern "C" int TINKER_MOD(faces, maxv);
extern "C" int TINKER_MOD(faces, maxen);
extern "C" int TINKER_MOD(faces, maxfn);
extern "C" int TINKER_MOD(faces, maxc);
extern "C" int TINKER_MOD(faces, maxep);
extern "C" int TINKER_MOD(faces, maxfs);
extern "C" int TINKER_MOD(faces, maxcy);
extern "C" int TINKER_MOD(faces, mxcyep);
extern "C" int TINKER_MOD(faces, maxfp);
extern "C" int TINKER_MOD(faces, mxfpcy);
extern "C" int TINKER_MOD(faces, na);
extern "C" double TINKER_MOD(faces, pr);
extern "C" double* TINKER_MOD(faces, ar);
extern "C" double* TINKER_MOD(faces, axyz);
extern "C" int* TINKER_MOD(faces, skip);
extern "C" int* TINKER_MOD(faces, nosurf);
extern "C" int* TINKER_MOD(faces, afree);
extern "C" int* TINKER_MOD(faces, abur);
extern "C" int* TINKER_MOD(faces, cls);
extern "C" int* TINKER_MOD(faces, clst);
extern "C" int* TINKER_MOD(faces, acls);
extern "C" int TINKER_MOD(faces, ntt);
extern "C" int* TINKER_MOD(faces, ttfe);
extern "C" int* TINKER_MOD(faces, ttle);
extern "C" int* TINKER_MOD(faces, enext);
extern "C" int* TINKER_MOD(faces, tta);
extern "C" int* TINKER_MOD(faces, ttbur);
extern "C" int* TINKER_MOD(faces, ttfree);
extern "C" int TINKER_MOD(faces, nt);
extern "C" int* TINKER_MOD(faces, tfe);
extern "C" int* TINKER_MOD(faces, ta);
extern "C" double* TINKER_MOD(faces, tr);
extern "C" double* TINKER_MOD(faces, t);
extern "C" double* TINKER_MOD(faces, tax);
extern "C" int* TINKER_MOD(faces, tfree);
extern "C" int TINKER_MOD(faces, np);
extern "C" int* TINKER_MOD(faces, pa);
extern "C" double* TINKER_MOD(faces, p);
extern "C" int TINKER_MOD(faces, nv);
extern "C" int* TINKER_MOD(faces, va);
extern "C" int* TINKER_MOD(faces, vp);
extern "C" double* TINKER_MOD(faces, vxyz);
extern "C" int TINKER_MOD(faces, nen);
extern "C" int TINKER_MOD(faces, nfn);
extern "C" int* TINKER_MOD(faces, env);
extern "C" int* TINKER_MOD(faces, fnen);
extern "C" int TINKER_MOD(faces, nc);
extern "C" int* TINKER_MOD(faces, ca);
extern "C" int* TINKER_MOD(faces, ct);
extern "C" double* TINKER_MOD(faces, cr);
extern "C" double* TINKER_MOD(faces, c);
extern "C" int TINKER_MOD(faces, nep);
extern "C" int* TINKER_MOD(faces, epc);
extern "C" int* TINKER_MOD(faces, epv);
extern "C" int* TINKER_MOD(faces, afe);
extern "C" int* TINKER_MOD(faces, ale);
extern "C" int* TINKER_MOD(faces, epnext);
extern "C" int TINKER_MOD(faces, nfs);
extern "C" int* TINKER_MOD(faces, fsen);
extern "C" int* TINKER_MOD(faces, fsep);
extern "C" int TINKER_MOD(faces, ncy);
extern "C" int* TINKER_MOD(faces, cynep);
extern "C" int* TINKER_MOD(faces, cyep);
extern "C" int TINKER_MOD(faces, nfp);
extern "C" int* TINKER_MOD(faces, fpa);
extern "C" int* TINKER_MOD(faces, fpncy);
extern "C" int* TINKER_MOD(faces, fpcy);

int& maxcls = TINKER_MOD(faces, maxcls);
int& maxtt = TINKER_MOD(faces, maxtt);
int& maxt = TINKER_MOD(faces, maxt);
int& maxp = TINKER_MOD(faces, maxp);
int& maxv = TINKER_MOD(faces, maxv);
int& maxen = TINKER_MOD(faces, maxen);
int& maxfn = TINKER_MOD(faces, maxfn);
int& maxc = TINKER_MOD(faces, maxc);
int& maxep = TINKER_MOD(faces, maxep);
int& maxfs = TINKER_MOD(faces, maxfs);
int& maxcy = TINKER_MOD(faces, maxcy);
int& mxcyep = TINKER_MOD(faces, mxcyep);
int& maxfp = TINKER_MOD(faces, maxfp);
int& mxfpcy = TINKER_MOD(faces, mxfpcy);
int& na = TINKER_MOD(faces, na);
double& pr = TINKER_MOD(faces, pr);
double*& ar = TINKER_MOD(faces, ar);
double*& axyz = TINKER_MOD(faces, axyz);
int*& skip = TINKER_MOD(faces, skip);
int*& nosurf = TINKER_MOD(faces, nosurf);
int*& afree = TINKER_MOD(faces, afree);
int*& abur = TINKER_MOD(faces, abur);
int*& cls = TINKER_MOD(faces, cls);
int*& clst = TINKER_MOD(faces, clst);
int*& acls = TINKER_MOD(faces, acls);
int& ntt = TINKER_MOD(faces, ntt);
int*& ttfe = TINKER_MOD(faces, ttfe);
int*& ttle = TINKER_MOD(faces, ttle);
int*& enext = TINKER_MOD(faces, enext);
int*& tta = TINKER_MOD(faces, tta);
int*& ttbur = TINKER_MOD(faces, ttbur);
int*& ttfree = TINKER_MOD(faces, ttfree);
int& nt = TINKER_MOD(faces, nt);
int*& tfe = TINKER_MOD(faces, tfe);
int*& ta = TINKER_MOD(faces, ta);
double*& tr = TINKER_MOD(faces, tr);
double*& t = TINKER_MOD(faces, t);
double*& tax = TINKER_MOD(faces, tax);
int*& tfree = TINKER_MOD(faces, tfree);
int& np = TINKER_MOD(faces, np);
int*& pa = TINKER_MOD(faces, pa);
double*& p = TINKER_MOD(faces, p);
int& nv = TINKER_MOD(faces, nv);
int*& va = TINKER_MOD(faces, va);
int*& vp = TINKER_MOD(faces, vp);
double*& vxyz = TINKER_MOD(faces, vxyz);
int& nen = TINKER_MOD(faces, nen);
int& nfn = TINKER_MOD(faces, nfn);
int*& env = TINKER_MOD(faces, env);
int*& fnen = TINKER_MOD(faces, fnen);
int& nc = TINKER_MOD(faces, nc);
int*& ca = TINKER_MOD(faces, ca);
int*& ct = TINKER_MOD(faces, ct);
double*& cr = TINKER_MOD(faces, cr);
double*& c = TINKER_MOD(faces, c);
int& nep = TINKER_MOD(faces, nep);
int*& epc = TINKER_MOD(faces, epc);
int*& epv = TINKER_MOD(faces, epv);
int*& afe = TINKER_MOD(faces, afe);
int*& ale = TINKER_MOD(faces, ale);
int*& epnext = TINKER_MOD(faces, epnext);
int& nfs = TINKER_MOD(faces, nfs);
int*& fsen = TINKER_MOD(faces, fsen);
int*& fsep = TINKER_MOD(faces, fsep);
int& ncy = TINKER_MOD(faces, ncy);
int*& cynep = TINKER_MOD(faces, cynep);
int*& cyep = TINKER_MOD(faces, cyep);
int& nfp = TINKER_MOD(faces, nfp);
int*& fpa = TINKER_MOD(faces, fpa);
int*& fpncy = TINKER_MOD(faces, fpncy);
int*& fpcy = TINKER_MOD(faces, fpcy);
#endif
} TINKER_NAMESPACE_END

#endif
